### ISSUE TITLE
app crashes 

### ISSUE THREAD

**Issue by Sohel3798** [massijay/iOSMauiScrollUpOnKeyboardShow#2]
app crashes after added <controls:FixedScrollView> and UIViewExtensions

https://drive.google.com/file/d/11TYUGARFSQisURRnA491VGXzCOt-xj7B/view?usp=sharing

**Comment by massijay** [comment]
I can't really help you with that little information provided, anyway have no time right now to look into the issue since I'm not using MAUI at the moment.

**Comment by Sohel3798** [comment]
> I can't really help you with that little information provided, anyway have no time right now to look into the issue since I'm not using MAUI at the moment.

can you tell me what what things you added for fix keyboard overlapping that will help me a lot

**Comment by massijay** [comment]
You can see all I added in this commit dd04f737887cac466887b64f065e68071c853f75

**Comment by Sohel3798** [comment]
> You can see all I added in this commit [dd04f73](https://github.com/massijay/iOSMauiScrollUpOnKeyboardShow/commit/dd04f737887cac466887b64f065e68071c853f75)

Thanks sir i followed same flow but facing crash

**Comment by massijay** [comment]
If you try to build and run this repo it crashes too?

**Comment by Sohel3798** [comment]
> If you try to build and run this repo it crashes too?

no repo code working fine 😢

**Comment by massijay** [comment]
If you use the default ScrollView it crashes?

**Comment by Sohel3798** [comment]
> If you use the default ScrollView it crashes?

no sir if i use fixedscrollview and exaction and when i click on entry then face the crash

**Comment by massijay** [comment]
Then all I can suggest is to try to debug the OnKeyboardShowing method of the FixedScrollView class

**Comment by Sohel3798** [comment]
> Then all I can suggest is to try to debug the OnKeyboardShowing method of the FixedScrollView class

founded the issue I'm not using app shell
